kz:
  jms:
    username: Vladimir Glinskikh
    password: somePassword
    url: someUrl

---
spring:
  profiles: de
kz:
  jms:
    username: Vladimir Glinskikh****IN**GERMAN

---
spring:
  profiles: ru
kz:
  jms:
    username: Vladimir Glinskikh****IN**RUSSIAN